api_version = "2025-10"

[[extensions]]
name = "dpd-print-from-order"
handle = "dpd-print-from-order"
type = "ui_extension"
uid = "5abf31d8-5e8b-6736-8548-5b846ed75732e8a40ab9"

[[extensions.targeting]]
module = "./src/PrintActionExtension.tsx"
target = "admin.order-details.print-action.render"

[[extensions]]
type = "ui_extension"
name = "DPD Bulk Print"
handle = "dpd-bulk-print"

uid = "23a01864-e561-3d27-6692-0873dff7c22fefff6b91"

[[extensions.targeting]]
module = "./src/BulkPrintExtension.tsx"
target = "admin.order-index.selection-print-action.render"