api_version = "2025-10"
[[extensions]]
name = "dpd-print-index"
handle = "dpd-print-index"
type = "ui_extension"
uid = "e5201313-ac38-701c-a47d-676c67e4f26c2e4bc045"

# Only 1 target can be specified for each admin print action extension
[[extensions.targeting]]
module = "./src/PrintActionExtension.tsx"
target = "admin.order-index.selection-print-action.render"

# Valid extension targets:

# - admin.order-details.print-action.render
# - admin.order-index.selection-print-action.render
# - admin.product-details.print-action.render
# - admin.product-index.selection-print-action.render
